### ISSUE TITLE
Be able to type multiple arguments on mutation functions

### ISSUE THREAD

**Issue by kevinrodriguez-io** [sergiodxa/use-mutation#110]
![1](https://user-images.githubusercontent.com/6248571/115761884-0fab3b00-a360-11eb-96db-09d3d3f4b13b.jpg)

Above example will work but I had to set any as input.

**Is your feature request related to a problem? Please describe.**
- Yes, I'm unable to type multiple input args.

**Describe the solution you'd like**
- An example or api that allows for multiple args to be sent.

**Describe alternatives you've considered**
- As of now only `any`, but maybe changing the order of the generic arguments or creating overloads could also do the trick.

**Additional context**

**Comment by sergiodxa** [comment]
The example in the README shows how to use a function with more than one argument, you need to make your function receive a single object with all your arguments.

if you are trying to use this hook with a function you don’t control and it receives more than one argument you would need to create a wrapper to receive the object and call your actual function passing the properties as different arguments.
